version: "3"

services:
  app:
    build: .
    command: sh -c "$(go env GOPATH)/bin/air"
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  ngrok:
    command: start --all --config /etc/ngrok.yml
    env_file:
      - .env
    image: ngrok/ngrok
    ports:
      - "4040:4040"
    restart: unless-stopped
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
